name: null
favicon: null
layout_spectrum: 0.43125419854186475
typography_spectrum: 0.031712430296465755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5403350624255836
  lightness: 0.8705680374987423
  saturation: 0.06821694923564792
  rhythmicContrast: 0.3762507769279182
purpose: []
